CREATE TABLE RDS_ORCAMENTO (
	ORCAMENTOID INT NOT NULL CONSTRAINT PK_RDS_ORCAMENTO PRIMARY KEY,
	IDRDSTATION VARCHAR(50) NOT NULL,
	CREATEDAT DATETIME NOT NULL,
	UPDATEDAT DATETIME NOT NULL,
	UPDATEDTIMES INT NOT NULL);