CREATE TABLE RDS_PARCEIRO (
	PARCEIROID INT NOT NULL CONSTRAINT PK_RDS_PARCEIRO PRIMARY KEY,
	IDRDSTATION VARCHAR(50) NOT NULL,
	CREATEDAT DATETIME NOT NULL,
	UPDATEDAT DATETIME NOT NULL,
	UPDATEDTIMES INT NOT NULL);