SELECT TOP 10 
	PRD.PRODUTOID,
	RDS.IDRDSTATION,
	PRD.CODESTOQUE,
	PRD.DESCRICAO,
	CAST(0.0 AS NUMERIC(10,2)) AS PRECO,
	CASE WHEN RDS.PRODUTOID IS NULL THEN 'I' ELSE 'U' END INSORUPD
FROM EST_PRODUTO PRD
	LEFT JOIN RDS_Produto RDS ON RDS.PRODUTOID = PRD.PRODUTOID
WHERE RDS.PRODUTOID IS NULL OR RDS.UPDATEDAT < PRD.DTALTERACAO
ORDER BY PRD.PRODUTOID;