SELECT
    ITM.PRODUTOID, 
    PRO.CODESTOQUE AS NOME, 
    PRO.DESCRICAO,
    ITM.QTDSALDO,
    ITM.VRUNITARIO,
    ITM.QTDPRODUTO,
	ITM.VRUNITARIO * ITM.QTDPRODUTO AS TOTAL,
	'' AS DISCOUNT_TYPE,
	'' AS RECURRENCE
FROM VDA_ORCAMENTOITEM ITM
     JOIN EST_PRODUTO PRO ON PRO.PRODUTOID = ITM.PRODUTOID
WHERE ITM.ORCAMENTOID = :ORCAMENTOID
ORDER BY PRO.DESCRICAO;