SELECT TOP 10
    ORC.ORCAMENTOID,-- numero do orcamento / oportunidade
    RDO.IDRDSTATION,
    'ORÇAMENTO #' + CAST(ORC.ORCAMENTOID AS VARCHAR) AS NOMEORCAMENTO,
    1 AS RATING,
    PED.PEDIDOID,
    ORC.DTEMISSAO,   -- dt emissao da oportunidade
    ORC.PARCEIROID, --parceiroid /empresa da oportunidade
    RDP.IDRDSTATION AS RDSPARCEIROID,
    ORC.PARCEIROCONTATOID, -- Contato da opotunidade
    RDC.IDRDSTATION AS RDSCONTATOID,
    COALESCE(COM.CODEXTERNO, '') AS USERID, --id do usuário responsável / vendedor
    'S7' AS DEALSOURCE, --source da oportunidade
    '' AS CAMPAIGN,
    '' AS ORGANIZATION,
    COALESCE(STT.CODEXTERNO, '') AS DEALSTAGEID, --status do funil
    CASE WHEN (PED.PEDIDOID IS NOT NULL) THEN 'S' ELSE 'N' END AS PROPOSTAGANHA,
    -- ORC.DTALTERACAO, -- vou ter que colocar no sistema.
    PED.DTALTERACAO ORCAMENTODTALTERACAO,
    PED.DTALTERACAO PEDIDODTALTERACAO,
    CASE WHEN RDO.ORCAMENTOID IS NULL THEN 'I' ELSE 'U' END INSORUPD
FROM VDA_ORCAMENTO ORC
LEFT JOIN VDA_PEDIDO PED ON PED.pedidoid = ORC.pedidoid
LEFT JOIN VDA_COMISSIONADO COM ON COM.COMISSIONADOID = ORC.VENDEDORID
LEFT JOIN VDA_STATUS STT ON STT.STATUSID = ORC.STATUSFOLLOWUPID
LEFT JOIN RDS_PARCEIRO RDP ON RDP.PARCEIROID = ORC.PARCEIROID
LEFT JOIN RDS_CONTATO RDC ON RDC.CONTATOID = ORC.PARCEIROCONTATOID
LEFT JOIN RDS_ORCAMENTO RDO ON RDO.ORCAMENTOID = ORC.ORCAMENTOID
WHERE ORC.DTEMISSAO >= :DATAEMISSAO
ORDER BY ORC.ORCAMENTOID, PED.PEDIDOID;